import React from "react";
import Head from "next/head";
import Image from "next/image";
import Header from "@/components/Header";
import bgimg from "../assets/images/contact-bg.png";
import { Centers } from "@/components/homecard";
import { Media } from "@/components/media";
import Footer from "@/components/Footer";

export default function Contact() {

  const CentersData = [
    {
      title: "MANZINI SERVICE CENTRE",
      description:
        "Sivuno Building, <br /> Ground floor, adjacent to Estel <br /> House, Manzini <br /> MANZINI",
    },
    {
      title: "MATSAPHA BRANCH",
      description: "Matsamo Shopping Complex <br /> (kaMahhala) <br /> MATSAPHA",
    },
    {
      title: "MBABANE SERVICE CENTRE",
      description:
        "3rd Floor, Corporate Place, Swazi <br /> Plaza <br /> MBABANE",
    },
    {
      title: "NHLANGANO BRANCH",
      description:
        "Old Skonkwane Building <br /> Corner of 6th Street and 3rd Avenue <br /> NHLANGANO",
    },
    {
      title: "PIGGS PEAK SERVICE CENTRE",
      description:
        "1st Floor, Supreme Building <br /> Evelyn Baring Road <br /> PIGGS PEAK",
    },
    {
      title: "SITEKI SERVICE CENTRE",
      description: "Mafumbe Building <br /> Jacaranda Road <br /> SITEKI",
    },
  ];

  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      {/*-----------------------Header---------------------*/}

      <Header />

      {/*------------------Contact Background-------------------*/}

      <section>
        <div className="relative">
          <Image src={bgimg} alt="" className="w-full" />
          <div className="absolute bottom-0 bg-white/80 w-full pl-10 py-[14px]">
            <h1 className="text-subColor text-3xl font-bold leading-8">
              CONTACT ERS
            </h1>
          </div>
        </div>
      </section>

      {/*------------------Head Section-------------------*/}

      <section>
        <div className="px-10 flex">
          <div className="flex flex-col gap-8 bg-subColor text-[#f5f5f5] pl-10 pr-12 pt-9 pb-16 w-[32%]">
            <div>
              <h1 className="text-xl font-bold leading-6 mb-1">
                Head Quarters
              </h1>
              <p className="text-sm leading-6 font-normal">
                Portion 419 of Farm 50, Along MR103,
              </p>
              <p className="text-sm leading-6 font-normal">Ezulwini</p>
              <p className="text-sm leading-6 font-normal">
                GPS Coordinates S 26 25.120 E 31 10.623
              </p>
              <p className="text-sm leading-6 font-normal">[+268] 2406 4000</p>
            </div>
            <div className="pr-6">
              <h1 className="text-xl font-bold leading-6 mb-1">
                ERS Contact Centre -
              </h1>
              <p className="text-sm leading-6 font-normal">
                For all your tax related enquiries call or email
              </p>
              <p className="text-sm leading-6 font-normal">
                the ERS Contact Centre on
              </p>
              <p className="text-sm leading-6 font-normal">[+268] 2406 4050</p>
              <p className="text-sm leading-6 font-normal">[+268] 2406 4000</p>
              <p className="text-sm leading-6 font-normal">
                WhatsApp 7606 3735
              </p>
              <p className="text-sm leading-6 font-normal">info@ers.org.sz</p>
            </div>
          </div>
          <div className="px-[40px] pt-9 bg-[#F5F5F5] w-[68%]">
            <h1 className="text-xl text-mainColor font-bold leading-8">
              Service Centers and Branches
            </h1>
            <div className="grid grid-cols-3 gap-x-16 gap-y-10 pt-5">
              {CentersData.map((item, key) => (
                <Centers
                  key={key}
                  title={item.title}
                  description={item.description}
                />
              ))}
            </div>
          </div>
        </div>
        {/* Map */}
        <div className="px-10">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4331.816287766545!2d31.17508431726318!3d-26.       418809908319176!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1ee8cee83ab4d14b%3A0x2c8213d352acb5f3!2sEswatini%20Revenue%20Service!5e0!3m2!1sen!2sin!4v1680769959819!5m2!1sen!2sin"
            width={"100%"}
            height={"420"}
            style={{ border: 0 }}
            allowFullScreen=""
            loading="lazy"
            referrerPolicy="no-referrer-when-downgrade"
          ></iframe>
        </div>
      </section>

      {/*------------------Social Media-------------------*/}

      <Media />

      {/*------------------Footer-------------------*/}

      <Footer />
    </>
  );
}
