import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Banner from "../assets/images/contact-bg.png";

export default function Error() {
  return (
    <>
      <Head>
        <title>ERS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      {/*-----------------------Header---------------------*/}

      <Header />

      {/*-----------------------Error---------------------*/}

      <section className="mb-10">
        <div className="relative flex items-center justify-center">
          <Image
            src={Banner}
            alt="..."
            className="brightness-[.35] w-full h-96"
          />
          <p className="text-6xl absolute text-white font-bold">Error Page</p>
        </div>

        <div className="text-subColor flex flex-col gap-4 items-center">
          <div class="relative flex justify-center items-center">
            <span className="text-[250px] leading-none tracking-wide text-bold text-mainColor">
              404
            </span>
            <div className="w-full absolute bg-white text-black text-3xl py-2 mt-7 text-center font-medium">
              Not Found
            </div>
          </div>
          <div className="flex flex-col gap-5">
            <p className="text-black/80 text-4xl flex justify-center font-medium">
              Something went wrong, try later
            </p>
            <p className="text-black text-xl leading-3 flex justify-center">
              You may have mistyped the address or the page may have moved.
            </p>
          </div>
          <Link href={"/"}>
            <button className="text-white hover:bg-opacity-75 bg-black text-xl font-bold border hover:border-black rounded-lg py-4 px-7 mt-5">
              Back To Home
            </button>
          </Link>
        </div>
      </section>

      {/*-----------------------Footer---------------------*/}

      <Footer />
    </>
  );
}
