import React, { useState } from "react";
import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Image from "next/image";
import Banner from "../assets/images/bg4.jpg";
import { BsQuestionCircle } from "react-icons/bs";
import { FiPlusCircle, FiMinusCircle } from "react-icons/fi";

export default function FAQ() {
  const [isOpen1, setIsOpen1] = useState(false);
  const [isOpen2, setIsOpen2] = useState(false);
  const [isOpen3, setIsOpen3] = useState(false);

  const toggleFAQ1 = () => {
    setIsOpen1(!isOpen1);
  };

  const toggleFAQ2 = () => {
    setIsOpen2(!isOpen2);
  };

  const toggleFAQ3 = () => {
    setIsOpen3(!isOpen3);
  };

  return (
    <>
      <Head>
        <title>ERS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      {/*-----------------------Header---------------------*/}

      <Header />

      <section>
        <Image src={Banner} alt="..." className="h-96 w-full" />
      </section>

      <section className=" mx-72 my-14">
        <div>
          <h1 className="text-subColor text-6xl font-bold uppercase">FAQ</h1>
          <p className="mt-6 text-gray-500 leading-normal font-normal text-lg">
            The Frequently Asked Questions (FAQ) section is updated with
            information on how to use the eCustoms Tariff for Eswatini, the SRA
            Tariff Book in general and the World Customs Organisation (WCO)
            Harmonised System on which it is based. The WCO FAQ on the
            Harmonised System can be accessed here.
          </p>
          <div className="mt-12">
            <div className="border-1 solid bg-[#F4F3F6] rounded-lg py-4 mb-4">
              <h1
                className="flex items-center justify-between gap-4 mx-4 cursor-pointer font-medium"
                onClick={toggleFAQ1}
              >
                <BsQuestionCircle className="text-3xl text-subColor" />I know
                that a rate of duty has recently changed, but I want to see what
                the rate was six months ago. How can I do that?
                {isOpen1 ? (
                  <FiMinusCircle className="text-2xl" />
                ) : (
                  <FiPlusCircle className="text-2xl" />
                )}
              </h1>
              {isOpen1 && (
                <div className="mx-14 mt-4 text-gray-500 leading-normal font-normal text-sm text-justify">
                  Using the Simulation Date field, select the applicable date
                  and search for the tariff code. The rate of duty that will
                  display will be as per the simulation date.
                </div>
              )}
            </div>

            <div className="border-1 solid bg-[#F4F3F6] rounded-lg py-4 mb-4">
              <h1
                className="flex items-center justify-between gap-4 mx-4 cursor-pointer font-medium"
                onClick={toggleFAQ2}
              >
                <BsQuestionCircle className="text-[43px] text-subColor" /> I am
                not certain of the tariff code I am looking for, but I know the
                chapter. What is the best way to be able to look through a
                number of tariff codes to identify the one I want?
                {isOpen2 ? (
                  <FiMinusCircle className="text-4xl" />
                ) : (
                  <FiPlusCircle className="text-4xl" />
                )}
              </h1>
              {isOpen2 && (
                <div className="mx-14 mt-4 text-gray-500 leading-normal font-normal text-sm text-justify">
                  Using the Tariff Browse functionality, go to the relevant
                  Section and Chapter. Click on the chapter to display all
                  tariff codes falling under that chapter. Alternatively, simply
                  enter the chapter number in the Tariff Search to display all
                  tariff codes for that chapter.
                </div>
              )}
            </div>
            <div className="border-1 solid bg-[#F4F3F6] rounded-lg py-6 mb-4">
              <div
                className="flex items-center justify-between gap-4 mx-4 cursor-pointer"
                onClick={toggleFAQ3}
              >
                <BsQuestionCircle className="text-2xl text-subColor" />
                <h1 className="flex-1 text-lg font-medium">
                  I would like to find the rate of duty for a product.
                </h1>
                {isOpen3 ? (
                  <FiMinusCircle className="text-xl" />
                ) : (
                  <FiPlusCircle className="text-xl" />
                )}
              </div>
              {isOpen3 && (
                <div className="mx-14 mt-4 text-gray-500 leading-normal font-normal text-sm text-justify">
                  Using the Tariff Search or Tariff Browse functionality, find
                  the appropriate tariff code for the product. Click on the view
                  icon to display the current rates of duty. Alternatively, make
                  use of the Duty Estimator to estimate the rate of duty based
                  on the product’s country of origin and customs value.
                </div>
              )}
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </>
  );
}
