import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Banner from "../assets/images/gallery.jpg";
import { GallaryCard } from "@/components/media";
import { GalleryData } from "@/content/data";

export default function Gallery() {
  const [isVisible, setIsVisible] = useState({
    group1: true,
    group2: false,
    group3: false,
    group4: false,
    group5: false,
  });

  function toggleVisibility(groupName) {
    setIsVisible(() => {
      const newState = {
        [groupName]: [groupName],
      };
      return newState;
    });
  }

  const ImageTitle = ["Works", "Campagn", "Event", "Speech", "Vote"];

  return (
    <>
      <Head>
        <title>Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      {/*-----------------------Header---------------------*/}

      <Header />

      {/*-----------------------Banner---------------------*/}

      <section>
        <Image src={Banner} alt="..." className="h-96 w-full" />
      </section>

      {/*-----------------------Gallery---------------------*/}

      <section className="bg-white px-20 py-16">
        <div>
          <h1 className=" text-[#2F3192] text-4xl font-semibold">
            ERS Image Gallery
          </h1>
          <div className="border w-[264px] border-yellowish mt-2"></div>
        </div>

        {/* Group Indicator */}
        <div className="flex justify-center items-center gap-5 my-10">
          {ImageTitle.map((title, id) => (
            <button
              key={id}
              onClick={() => toggleVisibility(`group${id + 1}`)}
              className={`text-base text-black/80 bg-[#F7F7FA] text-center leading-6 font-semibold uppercase border border-[#ECECEC] rounded-full px-7 py-1 hover:text-white hover:bg-mainColor hover:ease-in hover:duration-300 ${
                isVisible[`group${id + 1}`]
                  ? "bg-mainColor text-white"
                  : "bg-[#F7F7FA] text-black/80"
              }`}
            >
              {title}
            </button>
          ))}
        </div>
        
        {/* Content First Group */}
        <div
          className={`grid grid-cols-3 px-3 ${
            isVisible.group1 ? "block" : "hidden"
          }`}
        >
          {GalleryData.group1.map((item, key) => (
            <GallaryCard
              key={key}
              img={item.img}
              group={item.group}
              date={item.date}
              description={item.description}
            />
          ))}
        </div>
        
        {/* Content Second Group */}
        <div
          className={`grid grid-cols-3 px-3 ${
            isVisible.group2 ? "block" : "hidden"
          }`}
        >
          {GalleryData.group2.map((item, key) => (
            <GallaryCard
              key={key}
              img={item.img}
              group={item.group}
              date={item.date}
              description={item.description}
            />
          ))}
        </div>

        {/* Content Third Group */}
        <div
          className={`grid grid-cols-3 px-3 ${
            isVisible.group3 ? "block" : "hidden"
          }`}
        >
          {GalleryData.group3.map((item, key) => (
            <GallaryCard
              key={key}
              img={item.img}
              group={item.group}
              date={item.date}
              description={item.description}
            />
          ))}
        </div>

        {/* Content Fourth Group */}
        <div
          className={`grid grid-cols-3 px-3 ${
            isVisible.group4 ? "block" : "hidden"
          }`}
        >
          {GalleryData.group4.map((item, key) => (
            <GallaryCard
              key={key}
              img={item.img}
              group={item.group}
              date={item.date}
              description={item.description}
            />
          ))}
        </div>

        {/* Content Fifth Group */}
        <div
          className={`grid grid-cols-3 px-3 ${
            isVisible.group5 ? "block" : "hidden"
          }`}
        >
          {GalleryData.group5.map((item, key) => (
            <GallaryCard
              key={key}
              img={item.img}
              group={item.group}
              date={item.date}
              description={item.description}
            />
          ))}
        </div>
      </section>

      {/*-----------------------Footer---------------------*/}

      <Footer />
    </>
  );
}
