import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { NewsData } from "@/content/data";
import Banner from "../assets/images/news-banner.jpg";
import Twitter from "../assets/images/twitter-page.jpg";
import Instagram from "../assets/images/insta-page.jpg";

export default function NewsDetails() {
  return (
    <>
      <Head>
        <title>Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      {/*-----------------------Header---------------------*/}

      <Header />

      {/*-----------------------Banner---------------------*/}

      <section>
        <Image src={Banner} alt="..." className="h-96 w-full" />
      </section>

      {/*-----------------------Detailed News---------------------*/}

      <section className="my-16 mx-20">
        <div className="grid w-full grid-cols-3 gap-20">
          <div className="col-span-2">
            {NewsData.map((item, id) => (
              <div key={id} className="flex flex-col gap-10">
                <h1 className="text-[38px] leading-6 font-semibold text-subColor">
                  {item.title}
                </h1>
                <h3 className="text-lg text-justify leading-7 font-medium text-black">
                  {item.head}
                </h3>
                <p className="text-base text-justify leading-[26px] font-normal text-black/80">
                  {item.about}
                </p>
                <Image src={item.img} alt="..." />
                <p className="text-base text-justify leading-[26px] font-normal text-black/80">
                  {item.para}
                </p>
                <p className="text-base text-justify leading-[26px] font-normal text-black/80">
                  {item.description}
                </p>
              </div>
            ))}
          </div>
          <div className="col-span-1 flex gap-8 flex-col">
            <iframe
              src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FEswatiniRevenueService&tabs=timeline&width=340&height=500&small_header=true&adapt_container_width=true&hide_cover=false&show_facepile=true&appId"
              width={"344"}
              height={"450"}
              style={{
                borderWidth: "2px",
                borderColor: "#DADAEB",
                cursor: "pointer",
              }}
              scrolling="no"
              frameBorder="0"
              allowFullScreen=""
              allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"
            ></iframe>
            <Link href="https://twitter.com/AECOM" target="_blank">
            <Image
              src={Twitter}
              alt=""
              width={"344"}
              height={"450px"}
              style={{
                borderWidth: "2px",
                borderColor: "#DADAEB",
                cursor: "pointer",
              }}
            />
            </Link>
              <Link href="https://www.instagram.com/aecom" target="_blank">

              <Image
                src={Instagram}
                alt=""
                width={"344"}
                height={"450px"}
                style={{
                  borderWidth: "2px",
                  borderColor: "#DADAEB",
                  cursor: "pointer",
                }}
              />
            </Link>
          </div>
        </div>
      </section>

      {/*-----------------------Footer---------------------*/}

      <Footer />
    </>
  );
}
